// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgzc1j0QMv4cpMe0rFPZB_VuX9yn3hPSI',
    appId: '1:268261800263:android:a4943f81a87dc73c8cb462',
    messagingSenderId: '268261800263',
    projectId: 'autoelkady-v2',
    storageBucket: 'autoelkady-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe_dl2DdbcSTuaHQZFS9NmytvD2_UslUA',
    appId: '1:268261800263:ios:1812af8cc2214e9e8cb462',
    messagingSenderId: '268261800263',
    projectId: 'autoelkady-v2',
    storageBucket: 'autoelkady-v2.firebasestorage.app',
    iosBundleId: 'com.example.autoelkady',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWXyWmCFpml2AYPeM8hSBTGbJlb74qvkM',
    appId: '1:268261800263:web:1e9733ad0a8721238cb462',
    messagingSenderId: '268261800263',
    projectId: 'autoelkady-v2',
    authDomain: 'autoelkady-v2.firebaseapp.com',
    storageBucket: 'autoelkady-v2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe_dl2DdbcSTuaHQZFS9NmytvD2_UslUA',
    appId: '1:268261800263:ios:1812af8cc2214e9e8cb462',
    messagingSenderId: '268261800263',
    projectId: 'autoelkady-v2',
    storageBucket: 'autoelkady-v2.firebasestorage.app',
    iosBundleId: 'com.example.autoelkady',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWXyWmCFpml2AYPeM8hSBTGbJlb74qvkM',
    appId: '1:268261800263:web:005f10efd42980968cb462',
    messagingSenderId: '268261800263',
    projectId: 'autoelkady-v2',
    authDomain: 'autoelkady-v2.firebaseapp.com',
    storageBucket: 'autoelkady-v2.firebasestorage.app',
  );

}